Fix up vm-support-lx.
. clean up indentation
. make it /bin/sh-friendly
. make it support FreeBSD and Solaris too
. stop packaging up /proc, which takes a long time and doesn't necessarily
help.
. don't follow symlinks (so that we don't package ICU data or plugins under
/etc/vmware-tools).
. package syslogs too.
. get rid of the spinning thing (progress "report") since it doesn't play
well with FreeBSD's/Solaris's /bin/echo.

Signed-off-by: Marcelo Vanzin <mvanzin@vmware.com>

diff --git a/open-vm-tools/scripts/common/vm-support b/open-vm-tools/scripts/common/vm-support
--- a/open-vm-tools/scripts/common/vm-support
+++ b/open-vm-tools/scripts/common/vm-support
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 ##########################################################
 # Copyright (C) 2006-2010 VMware, Inc. All rights reserved.
 #
@@ -17,11 +17,9 @@
 #
 ##########################################################
 
-
-
-#	Function: usage prints how to use this script
-
-function usage {
+# usage(): prints how to use this script
+usage()
+{
 	echo ""
 	echo "Usage: $0 [-h]"
 	echo "	-h prints this usage statement"
@@ -29,14 +27,14 @@ function usage {
 }
 
 
-TARFILE=vm-$(date -I).$$.tgz
-VER=0.87
+TARFILE=vm-`date +%Y-%m-%d`.$$.tar
+VER=0.88
 OUTPUT_DIR=vm-support.$$
 
-#	Function: banner prints any number of strings padded with
-#	newlines before and after.
-
-function banner {
+# banner(): prints any number of strings padded with
+# newlines before and after.
+banner()
+{
 	echo
 	for option in "$@"
 	do
@@ -45,8 +43,8 @@ function banner {
 	echo
 }
 
-#	The status constants are important and have to be kept
-#	in sync with VMware Workstation implementation
+# The status constants are important and have to be kept
+# in sync with VMware Workstation implementation
 
 #	vm-support script is not running
 VMSUPPORT_NOT_RUNNING=0
@@ -64,259 +62,241 @@ VMSUPPORT_UNKNOWN=100
 #internal state machine state for update
 update=0
 
-#	Updates the VM with the current state
-
-function UpdateState {
+# UpdateState($state): Updates the VM with the given state.
+UpdateState()
+{
    if [ $update -eq 1 ]; then
      vmware-xferlogs upd $1
    fi
 }
 
-function UpdateSpinner {
-        case $SPINNER in
-		"|")
-                        SPINNER="/"
-                ;;
+# addfile(): copies whatever files and directories you give it to
+# a self contained output directory for later tar'ing
+# Working on copies could slow this down with VERY large files but:
+# 1) We don't expect VERY large files
+# 2) Since /proc files can be copied this preserves the tree without
+#    having to cat them all into a file.
+# 3) tar barfs on open files like logs if it changes while it's tar'ing.
+#    Copying file first makes sure tar doesn't complain
+addfile()
+{
+   file=$1
 
-                "/")
-                        SPINNER="-"
-                ;;
+   dir=`dirname "$file"`
+   if [ ! -d "${OUTPUT_DIR}$dir" ]; then
+      mkdir -p "${OUTPUT_DIR}$dir"
 
-                "-")
-                        SPINNER="\\"
-                ;;
+      if [ $? != 0 ]; then
+         banner "Could not create ./${OUTPUT_DIR}$dir... " \
+                "Have you run out of disk space?" "Continuing"
+         return
+      fi
+   fi
 
-                "\\")
-                        SPINNER="|"
-                ;;
-
-                *)
-                        SPINNER="|"
-                ;;
-        esac
-        echo -en "\rPreparing Files: $SPINNER"
-}
-
-#	Function: addtar copies whatever files and directories you give it to
-#	a self contained output directory for later tar'ing
-#	Working on copies could slow this down with VERY large files but:
-#	1) We don't expect VERY large files
-#	2) Since /proc files can be copied this preserves the tree without
-#	   having to cat them all into a file.
-#	3) tar barfs on open files like logs if it changes while it's tar'ing.
-#          Copying file first makes sure tar doesn't complain
-
-
-function addtar {
-	FILE=$1
-
-	DIR=$(dirname "$FILE")
-	if [ ! -d "${OUTPUT_DIR}$DIR" ]; then
-		mkdir -p "${OUTPUT_DIR}$DIR"
-
-		if [ $? != 0 ]; then
-			banner "Could not create ./${OUTPUT_DIR}$DIR... " \
-				"Have you run out of disk space?" "Continuing"
-			return
-		fi
-	fi
-
-	# Ignore stdout and handle errors.
-	UpdateSpinner
-	cp -pr "$FILE" "${OUTPUT_DIR}$DIR" 2>/dev/null
-
-	# We could have failed to copy for several reasons
-	# If we path had a shell special character (* ? .)
-	# or if the file is in /proc
-	if [ $? != 0 ]; then
-		FILENAME=${FILE##*/}
-		for line in "$DIR"/$FILENAME
-		do
-			if [ -e "$line" ]; then
-				# Ignore stdout and handle errors.
-				UpdateSpinner
-				cp -pr "$line" "${OUTPUT_DIR}$DIR" 2>/dev/null
-
-				# If a file from /proc does not copy,
-				# ignore - they're funny.
-				# Otherwise, exit for failed copy.
-				if [ $? != 0 ]; then
-					echo "$line" | grep ^/proc > /dev/null
-
-					if [ $? != 0 ]; then
-						banner "Could not copy $line \
-							to the tar area."
-						return
-					fi	# Not proc
-				fi # is it proc
-			fi # does file exist
-
-		done # for each file in the list
-	fi # if copy failed
-
+   # Ignore stdout and handle errors.
+   cp -pRP "$file" "${OUTPUT_DIR}$dir" 2>/dev/null
+   if [ $? != 0 ]; then
+      banner "Could not copy '$file' to the tar area."
+   fi
 }
 
 
-#	Function: runcmd executes the command ($1)
-#	redirected to a file ($2) and then adds that
-#	file to the list of files to tar.
-#	It then deletes the temp file since addtar makes a copy in its own
-#	selft contained area.
+# addfiles(): adds a list of files to the archive.
+addfiles()
+{
+   for i in "$@"; do
+      addfile $i
+   done
+}
 
-function runcmd {
+
+# runcmd($cmd, $out): executes the command redirected to a file and then adds
+# that file to the list of files to tar. It then deletes the temp file since
+# addfile makes a copy in its own self-contained area.
+runcmd()
+{
 	$1 > $2 2>/dev/null
 
 	if [ $? != 0 ]; then
+	   echo 3
 		banner "Either could not run $1 or could not write to $2" \
-"Do you have a full disk?" "Continuing..."
+		       "Do you have a full disk? Continuing..."
 	else
-		addtar "$2"
-		rm "$2"
-
-		if [ $? != 0 ]; then
-			banner "Could not delete $2.  Continuing..."
-		fi
+		addfile "$2"
+		rm -f "$2"
 	fi
 }
 
+
+# error(): prints an error message using the "banner" funtion and quits.
+error()
+{
+   banner "$@"
+   UpdateState $VMSUPPORT_ERROR
+   exit 1
+}
 
 # Parse args
 for option in $@
 do
-        case $option in
-                "-h")
-                        usage
-                ;;
-                "-u")
-                        update=1
-                ;;
-                *)
-                        usage
-                ;;
-        esac
+   case $option in
+   "-h")
+      usage
+      ;;
+   "-u")
+      update=1
+      ;;
+   *)
+      usage
+      ;;
+   esac
 done
 
 #	Start message
 
 UpdateState $VMSUPPORT_BEGINNING
 
-banner "VMware Linux Support Script $VER"
+banner "VMware UNIX Support Script $VER"
 
 #	Check for root privledge
 
-if [ $(id -u) != "0" ]; then
-        banner "You are not root, some system information can't be collected."
+if [ `whoami` != 'root' ]; then
+   banner "You are not root, some system information can't be collected."
 fi
 
 # Source /etc/profile.  If we can't find it, it's the users problem to get
 # their paths straight.
-
 if [ -f /etc/profile ]; then
 	. /etc/profile
 fi
 
 # Protect against non-default values of $IFS (Not all scripts in /etc/profile.d/
 # are good citizens).
-unset IFS
+if [ `uname` != 'SunOS' ]; then
+   unset IFS 2>/dev/null
+fi
 
 #	make a subdir to put all your files in.  die if it does not create
 mkdir $OUTPUT_DIR
 
 if [ $? != 0 ]; then
-	banner "Could not create ./${OUTPUT_DIR}... Exiting..." \
-"Please cd to a directory to which you can write" # Thanks Adam!
-	exit
+	error "Could not create ./${OUTPUT_DIR}. Please cd to a directory to which "
+	      "you can write."
 fi
 
+banner "Collecting support information..."
 
-#	Add system configuration and log files. Wildcards
-#	may be used.
-
-
-# Try to collect bootloader config.
-if [ -e /etc/lilo.conf ]; then
-	addtar "/etc/lilo.conf"
-fi
-
-# And for grub we are not sure about the exact default location so collect them
-# all.
-if [ -e /boot/grub/grub.conf ]; then
-	addtar "/boot/grub/grub.conf"
-fi
-if [ -e /boot/grub/menu.lst ]; then
-        addtar "/boot/grub/menu.lst"
-fi
-if [ -e /etc/grub.conf ]; then
-        addtar "/etc/grub.conf"
-fi
-
-addtar "/etc/crontab"
-addtar "/etc/cron.daily"
-addtar "/etc/cron.hourly"
-addtar "/etc/cron.monthly"
-addtar "/etc/cron.weekly"
-addtar "/etc/modules.conf"
-addtar "/etc/ntp.conf"
-addtar "/etc/security/*"
-
-
-# Add services
-addtar "/etc/services"
-
-addtar "/etc/vmware-tools/*"
-addtar "/var/log/boot*"
-addtar "/var/log/secure*"
-addtar "/var/log/messages*"
-addtar "/var/run/vmware-*"
-
-# Add /proc with some exceptions.  stdout redirected to /dev/null.  Some files
-# come and go and confuse find.  Just send whatever works and don't scare user.
-
-for procfile in `find /proc -type f 2>/dev/null| egrep -v kcore\|kmsg\|acpi\|pagemap\|/proc/$$`
-do
-	addtar "$procfile"
-done
-
-#	Commands to run ($1) and redirect to logs ($2) for
-#	inclusion.
-
+# Common stuff that we gather for all OSes.
 runcmd "echo vm-support version: $VER" "/tmp/vm-support-version.$$.txt"
-runcmd "lspci -H1 -M" "/tmp/lspci1.$$.txt"
-runcmd "lspci -H1 -M -vn" "/tmp/lspci2.$$.txt"
-runcmd "/sbin/lsmod" "/tmp/modules.$$.txt"
-runcmd "uname -a" "/tmp/uname.$$.txt"
+
+addfiles /etc/vmware-tools
+addfiles /var/log/boot*
+addfiles /var/log/secure*
+addfiles /var/log/messages*
+addfiles /var/log/syslog*
+addfiles /var/run/vmware-*
+
 runcmd "df" "/tmp/df.$$.txt"
-runcmd "cat /etc/issue" "/tmp/issue.$$.txt"
 runcmd "ifconfig -a" "/tmp/ifconfig.$$.txt"
-runcmd "rpm -qa" "/tmp/rpm-qa.$$.txt"
-runcmd "netstat -lan" "/tmp/netstat-lan.$$.txt"
-runcmd "route" "/tmp/route.$$.txt"
 runcmd "mount" "/tmp/mount.$$.txt"
 runcmd "dmesg" "/tmp/dmesg.$$.txt"
-runcmd "free" "/tmp/free.$$.txt"
+runcmd "ulimit -a" "/tmp/ulimit-a.$$.txt"
 runcmd "uptime" "/tmp/uptime.$$.txt"
 runcmd "date" "/tmp/date.$$.txt"
-runcmd "ps auwwx" "/tmp/ps-auwwx.$$.txt"
-runcmd "ulimit -a" "/tmp/ulimit-a.$$.txt"
 runcmd "umask" "/tmp/umask.$$.txt"
+
+
+# stageLinux(): gather information for troubleshooting Linux guests.
+stageLinux()
+{
+   # Try to collect bootloader config.
+   if [ -e /etc/lilo.conf ]; then
+      addfiles /etc/lilo.conf
+   fi
+
+   # And for grub we are not sure about the exact default location so collect them
+   # all.
+   if [ -e /boot/grub/grub.conf ]; then
+      addfile /boot/grub/grub.conf
+   fi
+   if [ -e /boot/grub/menu.lst ]; then
+      addfile /boot/grub/menu.lst
+   fi
+   if [ -e /etc/grub.conf ]; then
+      addfile /etc/grub.conf
+   fi
+
+   addfile /etc/cron.daily
+   addfile /etc/cron.hourly
+   addfile /etc/cron.monthly
+   addfile /etc/cron.weekly
+   addfile /etc/crontab
+   addfile /etc/modules.conf
+   addfile /etc/ntp.conf
+   addfile /etc/security
+   addfile /etc/services
+
+   # Commands to run ($1) and redirect to logs ($2) for inclusion.
+   runcmd "lspci -H1 -M" "/tmp/lspci1.$$.txt"
+   runcmd "lspci -H1 -M -vn" "/tmp/lspci2.$$.txt"
+   runcmd "/sbin/lsmod" "/tmp/modules.$$.txt"
+   runcmd "uname -a" "/tmp/uname.$$.txt"
+   runcmd "cat /etc/issue" "/tmp/issue.$$.txt"
+   runcmd "rpm -qa" "/tmp/rpm-qa.$$.txt"
+   runcmd "netstat -lan" "/tmp/netstat-lan.$$.txt"
+   runcmd "route" "/tmp/route.$$.txt"
+   runcmd "free" "/tmp/free.$$.txt"
+}
+
+
+# stageFreeBSD(): gather information for troubleshooting FreeBSD guests.
+stageFreeBSD()
+{
+   runcmd "ps auwwx" "/tmp/ps-auwwx.$$.txt"
+}
+
+# stageSolaris(): gather information for troubleshooting Solaris guests.
+stageSolaris()
+{
+   runcmd "ps eaf" "/tmp/ps-eaf.$$.txt"
+}
+
+case `uname` in
+Linux)
+   stageLinux
+   #	tar options: 'S' for sparse core files.
+   TAR_OPTS=-cSf
+   ;;
+FreeBSD)
+   stageFreeBSD
+   TAR_OPTS=-cf
+   ;;
+SunOS)
+   stageSolaris
+   TAR_OPTS=-cf
+   ;;
+esac
 
 UpdateState $VMSUPPORT_RUNNING
 
-
-#	Perform the tar ('S' for sparse core files)
-
-tar -czSvf $TARFILE $OUTPUT_DIR
+banner "Creating tar archive..."
+tar $TAR_OPTS $TARFILE $OUTPUT_DIR
 
 if [ $? != 0 ]; then
-	banner "The tar did not successfully complete!" \
-"If tar reports that a file changed while reading, please attempt to rerun this script."
+	banner "The tar process did not successfully complete!" \
+	       "If tar reports that a file changed while reading, please attempt " \
+	       "to rerun this script."
 fi
 
-vmware-xferlogs enc $TARFILE &>/dev/null
+gzip $TARFILE
+TARFILE=${TARFILE}.gz
+
+banner "Uploading archive to host..."
+vmware-xferlogs enc $TARFILE 2>/dev/null
 
 if [ $? != 0 ]; then
-        banner "could not transmit logs successfully, either the xmitLogs"\
-        "binary is not in the path, or you are not in a virtual machine"
+   banner "Could not transmit logs successfully: either the vmware-xferlogs " \
+          "binary is not in the path, or you are not in a virtual machine."
 fi
 
 #	Clean up temporary files
@@ -327,5 +307,5 @@ if [ $? != 0 ]; then
 fi
 
 UpdateState $VMSUPPORT_ENDING
+banner "Done, support data available in '$TARFILE'."
 
-#	End
