Prepare files for 9.0.0 release.
Signed-off-by: Dmitry Torokhov <dtor@vmware.com>

diff --git a/open-vm-tools/scripts/linux/network b/open-vm-tools/scripts/linux/network
--- a/open-vm-tools/scripts/linux/network
+++ b/open-vm-tools/scripts/linux/network
@@ -47,34 +47,57 @@ echo
 #
 
 find_networking_script() {
-    local script="error"
-    for dir in "/etc/init.d" "/sbin/init.d" "/etc" "/etc/rc.d" ; do
-        if [ -d "$dir/rc0.d" ] &&
-	    [ -d "$dir/rc1.d" ] &&
-	    [ -d "$dir/rc2.d" ] &&
-	    [ -d "$dir/rc3.d" ] &&
-	    [ -d "$dir/rc4.d" ] &&
-	    [ -d "$dir/rc5.d" ] &&
-	    [ -d "$dir/rc6.d" ]; then
+   local script="error"
+   for dir in "/etc/init.d" "/sbin/init.d" "/etc" "/etc/rc.d" ; do
+      if [ -d "$dir/rc0.d" ] &&
+         [ -d "$dir/rc1.d" ] &&
+         [ -d "$dir/rc2.d" ] &&
+         [ -d "$dir/rc3.d" ] &&
+         [ -d "$dir/rc4.d" ] &&
+         [ -d "$dir/rc5.d" ] &&
+         [ -d "$dir/rc6.d" ]; then
 
-	    # Now find the appropriate networking script.
-	    if [ -d "$dir/init.d" ]; then
-		if [ -x "$dir/init.d/network" ]; then
-		    script="$dir/init.d/network"
-		elif [ -x "$dir/init.d/networking" ]; then
-		    script="$dir/init.d/networking"
-		fi
-	    else
-		if [ -x "$dir/network" ]; then
-		    script="$dir/network"
-		elif [ -x "$dir/networking" ]; then
-		    script="$dir/networking"
-		fi
-	    fi
-        fi
-    done
+         # Now find the appropriate networking script.
+         if [ -d "$dir/init.d" ]; then
+            if [ -x "$dir/init.d/network" ]; then
+               script="$dir/init.d/network"
+            elif [ -x "$dir/init.d/networking" ]; then
+               script="$dir/init.d/networking"
+            fi
+         else
+            if [ -x "$dir/network" ]; then
+               script="$dir/network"
+            elif [ -x "$dir/networking" ]; then
+               script="$dir/networking"
+            fi
+         fi
+      fi
+   done
 
-    echo "$script"
+   echo "$script"
+}
+
+
+#
+# run_network_script --
+#
+# Finds out how to run the system's script used to control networking, and
+# runs it with the given argument (which should be one of the usual SysV
+# init script arguments).
+#
+run_network_script()
+{
+   script=`find_networking_script`
+   [ "$script" != "error" ] || Panic "Cannot find system networking script."
+
+   # Using SysV "service" if it exists, otherwise fall back to run the script directly
+   service=`which service 2>/dev/null`
+   if [ $? = 0 -a -n "$service" ]; then
+      serviceName=`basename "$script"`
+      "$service" "$serviceName" "$1"
+   else
+      "$script" "$1"
+   fi
 }
 
 
@@ -243,9 +266,6 @@ main() {
    exitCode=0
    activeList=/var/run/vmware-active-nics
 
-   networkScript=`find_networking_script`
-   [ "$networkScript" != "error" ] || Panic "Cannot find system networking script."
-
    # XXX Are these really necessary?  If so, we should have seen customer
    # complaints by now.
    which ifup >/dev/null 2>&1      || Panic "ifup not in search path."
@@ -260,7 +280,7 @@ main() {
          exitCode=$?
          if [ $exitCode != 0 ]; then
             save_active_NIC_list
-            "$networkScript" stop
+            run_network_script stop
             exitCode=$?
          fi
          ;;
@@ -282,9 +302,11 @@ main() {
             if [ ! -s $activeList ]; then
                save_active_NIC_list
             fi
-            # XXX Do we really want restart or is start sufficient?  Like, would
-            # using start avoid the problem mentioned above?
-            "$networkScript" restart
+
+            # We shall use start not restart here. Otherwise we may not be able
+            # to bring back active list on distros like sles11sp2
+            # -- PR 816791
+            run_network_script start
             rescue_NIC
             exitCode=$?
          fi
